
import "./globals.css";
import Navbar from "./components/Navbar";
import Hero from "./Landing/Hero";
import About from "./Landing/About";
import Projects from "./Landing/Projects";
import DotNavigation from "./components/DotNavigations";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <head>
        {/* Import Google Fonts */}
        <link
  href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Dancing+Script:wght@400;500;600;700&family=Press+Start+2P&family=Space+Grotesk:wght@400;500;600;700&display=swap"
  rel="stylesheet"/>
      </head>
 
      <body>
      <Navbar/>
        <Hero/>
        <DotNavigation /> {/* Place the DotNavigation here */}
        <div id="about">
          <About />
        </div>
        <div id="projects">
          <Projects />
        </div>
        {children}
      </body>
    </html>
  );
}
